/*import org.openqa.selenium.WebDriver;
// import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class test1 {
    public static void main(String[] args) {
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\MNS\\Desktop\\chromedriver.exe");
        WebDriver obj = new ChromeDriver();
        obj.get("https://www.kitapyurdu.com/");
    }

} */
// Generated by Selenium IDE
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class TestHomePage {
        private WebDriver driver;
        private Map<String, Object> vars;
        JavascriptExecutor js;
        @Before
        public void setUp() {
                System.setProperty("webdriver.chrome.driver", "C:\\Users\\MNS\\Desktop\\chromedriver.exe");
                driver = new ChromeDriver();
                js = (JavascriptExecutor) driver;
                vars = new HashMap<String, Object>();
        }
        @After
        public void tearDown() {
                driver.quit();
        }
        @Test
        public void apply() {

                // 1 | open | / |
                driver.get("https://www.kitapyurdu.com/");
                // 2 | setWindowSize | 1304x768 |
                driver.manage().window().setSize(new Dimension(1304, 768));
                // 3 | click | id=search-input |
                driver.findElement(By.id("search-input")).click();
                // 4 | type | id=search-input | roman
                driver.findElement(By.id("search-input")).sendKeys("roman");
                // 5 | sendKeys | id=search-input | ${KEY_ENTER}
                driver.findElement(By.id("search-input")).sendKeys(Keys.ENTER);
                // 6 | click | css=#product-306815 .name span |
                driver.findElement(By.cssSelector("#product-306815 .name span")).click();
                // 7 | click | css=#button-cart > span |
                driver.findElement(By.cssSelector("#button-cart > span")).click();
                // 8 | click | id=cart-items |
                driver.findElement(By.id("cart-items")).click();
                // 9 | click | id=js-cart |
                driver.findElement(By.id("js-cart")).click();
                // 10 | click | name=quantity |
                driver.findElement(By.name("quantity")).click();
                // 11 | type | name=quantity | 2
                driver.findElement(By.name("quantity")).sendKeys("2");
                // 12 | click | css=.fa-refresh |
                driver.findElement(By.cssSelector(".fa-refresh")).click();
                // 13 | click | css=.red-icon |
                driver.findElement(By.cssSelector(".red-icon")).click();

        }

        public static void main(String[] args) {
                TestHomePage test = new TestHomePage();
                test.setUp();

          HomePage homepage = new HomePage(new ChromeDriver()) ;
          homepage.apply();
        }
}
